### ISSUE TITLE
Automatic redirect to https on SSL port

### ISSUE THREAD

**Issue by ArthurPatriot** [thepower/tpnode#2]
When trying open node API with SSL with `http://` got error. 

Add please redirect `http://` to `https://` for SSL node API.

Example:
1. https://power-node.allsteeply.com:1443/api/node/status - ✅
2. http://power-node.allsteeply.com:1443/api/node/status - 🛑 (add redirect to https)

**Comment by cleverfox** [comment]
It's not that easy to implement this. At 1443 ports listener starts TLS negotiation right after accepting client connection, this negotiation implemented inside SSL library. To change current behavior - it's needed to implement some kind of request parser which can distinguish HTTP query and TLS hello. But the most complex challenge is pushing received by such parser data (TLS hello or plain HTTP request) to handler module (as I can't push back in to the socket), because ssl:handshake can't get this data somehow other but reading from socket.
It might be implemented in future.
